// validators.ts

/**
 * Validate if the QR check-in token is valid.
 * Requires minimum 32 alphanumeric characters (no spaces).
 * Matches the format generated by generarTokensQR.ts.
 * @param {string} token - Token to validate.
 * @returns {boolean} - True if valid.
 */
export function validateToken(token: string): boolean {
  if (!token || typeof token !== 'string') return false;
  const trimmed = token.trim();
  const tokenRegex = /^[A-Za-z0-9]{32,}$/;
  return tokenRegex.test(trimmed);
}

/**
 * Validate if the given phone number is valid.
 * @param {string} phoneNumber - Phone number to validate.
 * @returns {boolean} - True if valid, false otherwise.
 */
function validatePhoneNumber(phoneNumber) {
    const phoneRegex = /^(\+\d{1,3}[- ]?)?\d{10}$/;
    return phoneRegex.test(phoneNumber);
}

/**
 * Validate if the given email is valid.
 * @param {string} email - Email to validate.
 * @returns {boolean} - True if valid, false otherwise.
 */
function validateEmail(email) {
    const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
    return emailRegex.test(email);
}

/**
 * Validate if the given date is valid.
 * @param {string} date - Date to validate in YYYY-MM-DD format.
 * @returns {boolean} - True if valid, false otherwise.
 */
function validateDate(date) {
    const dateRegex = /^(\d{4})-(\d{2})-(\d{2})$/;
    return dateRegex.test(date);
}

/**
 * Check if the required fields are present.
 * @param {Object} data - Data object to validate.
 * @param {Array<string>} requiredFields - List of required field names.
 * @returns {boolean} - True if all required fields are present, false otherwise.
 */
function validateRequiredFields(data, requiredFields) {
    return requiredFields.every(field => field in data);
}

export { validateToken, validatePhoneNumber, validateEmail, validateDate, validateRequiredFields };